### ISSUE TITLE
Lag when holding down `x` or `X`

### ISSUE THREAD

**Issue by evanrelf** [evanrelf/expand-line.kak#2]
The new selection is rendered as expected when repeatedly pressing <kbd>x</kbd> or <kbd>X</kbd>, but when holding down either key, the new selection isn't rendered until the key is released.

I believe this is because I'm running a shell command to detect whether the selection spans multiple lines, which is an expensive operation to be running repeatedly.

Replacing shell commands with native Kakoune `execute-keys` and/or `evaluate-commands` should eliminate this lag.

**Comment by evanrelf** [comment]
I haven't noticed this lag recently, and I'm not sure how to completely eliminate calls to the shell, so I'm going to close this.

**Comment by ficd0** [comment]
I managed to fix this lag in PR
