### ISSUE TITLE
Pressing "X" on a line with a single char doesn't do anything

### ISSUE THREAD

**Issue by Jackojc** [evanrelf/expand-line.kak#4]
If you have something like: 
```
{
    ...
}
```
and try to press X (shift-x, that is) on the `}`, nothing happens.

**Comment by evanrelf** [comment]
This plugin has a _lot_ of edge cases that I'm slowly fixing; thanks for bringing my attention to this one.

I won't have time to work on this plugin for a while, but I'll make sure to address this issue when I do.

**Comment by Jackojc** [comment]
Sounds good

**Comment by Jackojc** [comment]
Just wondering if there is any update on this issue?

**Comment by evanrelf** [comment]
Sorry, I don't have any updates. 

I do recognize it as a bug, and will leave this issue open until it gets fixed. But that may be a long time from now, or never, if I'm being honest.

I haven't run into this issue myself during regular use, and I also haven't been using Kakoune much recently, so I haven't been motivated to fix it.

**Comment by evanrelf** [comment]
This has been resolved in the latest fix (https://github.com/evanrelf/byline.kak/commit/a27d109b776c60e11752eeb3207c989a5e157fc0).

**Comment by Jackojc** [comment]
Thanks for resolving this!
