### ISSUE TITLE
`x` does not expand selection

### ISSUE THREAD

**Issue by need-4-sleep** [evanrelf/expand-line.kak#6]
Mashing `x` or `X` selects the line but does not expand below or above. For some reason though, typing `<num>x` (e.g. `3x`) works fine.

On latest version (v2023.08.05).

**Comment by evanrelf** [comment]
Hmm... I'm on the same version as you (v2023.08.05) and the plugin is working correctly. My initial reaction was "oh they must not have enabled the plugin correctly; they must be using the default behavior for `x` and `X`", but then I tried using the stock configuration (`kak -n`) and `3x` didn't work either.

Perhaps you, or a plugin you've installed, has re-mapped `x` and/or `X` to something else, so it's conflicting with `byline.kak`?

**Comment by need-4-sleep** [comment]
Okay so basically the issue is that I'm really dumb — for some reason I had the require module part commented out in `kakrc`. It works perfectly now, thank you for the plugin :)
